CityPantry/citypantry-3-frontend

src/web/js/controllers/admin/AdminMealPlanSetupMealPreferencesController.js
src/web/templates/admin/meal-plan-setup-meal-preferences.html
tests/unit/controllers/admin/AdminMealPlanSetupMealPreferencesController.spec.js

Fix package must have/must not have on the meal preferences page.

---

src/web/templates/admin/edit-customer.html

For faster debugging -- currently have to masquerade as the customer or look in the database to get this information.

Add delivery addresses to 'edit customer' page.

---

src/web/templates/general/staff-nav-menu-items.html
tests/e2e/general/NavigationMenu.js

Remove the Couriers link from the staff nav bar.

---

src/web/js/controllers/general/ViewPackageController.js
tests/unit/controllers/general/ViewPackageController.spec.js

Stop empty reviews from being displayed.

---

package.json
src/web/js/directives/cpReviewCardDirective.js
src/web/templates/directives/cp-review-card.html
src/web/templates/general/view-package.html

Depends on https://github.com/CityPantry/citypantry-3-api/pull/405

Allow staff to toggle review privacy.

---

src/web/js/directives/cpReviewCardDirective.js
tests/unit/directives/cpReviewCardDirective.spec.js

Add tests for Review Card.

---

Gruntfile.js
app/Resources/views/base.html.twig
app/config/config.yml
app/config/parameters.yml.dist
etc/karma.conf.js
src/web/js/angulartics-citypantry.js
src/web/js/app.module.js
src/web/js/config.js
src/web/js/controllers/admin/AdminDatabaseQueryController.js
src/web/scss/admin/database-query.scss
src/web/scss/main.scss
src/web/templates/admin/database-query.html
src/web/templates/general/staff-nav-menu-items.html
tests/e2e/admin/DatabaseQuery.js
tests/e2e/general/NavigationMenu.js
tests/unit/controllers/admin/AdminMealPlanSetupMealPreferencesController.spec.js
tests/unit/controllers/general/ViewPackageController.spec.js
tests/unit/mocks.js

Database integration

---

src/web/js/config.js
src/web/js/controllers/vendor/VendorQuickRegisterController.js
src/web/js/controllers/vendor/VendorQuickRegisterThankYouController.js
src/web/scss/main.scss
src/web/scss/vendor/signup.scss
src/web/templates/vendor/vendor-quick-register-thank-you.html
src/web/templates/vendor/vendor-quick-register.html
tests/unit/controllers/vendor/VendorQuickRegisterController.spec.js

Vendor signup

---

src/web/templates/customer/dashboard.html

Move the postcode field on the dashboard.

---

src/web/js/controllers/admin/AdminOrdersController.js
src/web/templates/admin/orders.html

Add total order amount to orders page.

---

src/web/js/controllers/admin/AdminCustomersController.js
tests/e2e/admin/Customers.js

Add customer company to admin customers page

---

package.json
src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/templates/admin/edit-customer.html
tests/e2e/admin/Customer.js

Allow staff to set customer as meal plan

---

src/web/templates/general/checkout-thank-you.html
tests/e2e/general/Checkout.js

Ticket: CPD-176 https://citypantry.atlassian.net/browse/CPD-176

Change wording on order success page.

---

src/web/js/controllers/general/SearchController.js
src/web/js/services/SearchService.js
src/web/scss/partials/_cp-forms.scss
src/web/scss/partials/_cp-search.scss
src/web/templates/general/search.html
tests/e2e/general/Search.js

Add filter to search by package name and vendor name.

---

src/web/js/directives/cpReviewMealPlanDirective.js
src/web/scss/directives/cp-review-meal-plan.scss
src/web/templates/directives/cp-review-meal-plan.html
tests/unit/directives/cpReviewMealPlanDirective.spec.js

Add week seperator between meal plan orders.

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminEditOrderDeliveryStatusController.js
src/web/templates/admin/edit-order-delivery-status.html
src/web/templates/admin/edit-order.html
tests/e2e/admin/EditOrderDeliveryStatus.js

Ticket: https://citypantry.atlassian.net/browse/CPD-185

Add page for staff to edit an order's delivery status.

---

package.json
src/web/js/controllers/admin/AdminCustomersController.js
src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/templates/admin/edit-customer.html
tests/e2e/admin/Customer.js
tests/e2e/admin/Customers.js

Show and allow editing of customer personas in the staff pages.

---

tests/e2e/admin/CourierOrders.js
tests/e2e/admin/Customers.js
tests/e2e/admin/Invoices.js
tests/e2e/admin/MealPlanDashboard.js
tests/e2e/admin/Orders.js
tests/e2e/admin/Packages.js
tests/e2e/admin/Users.js
tests/e2e/admin/Vendors.js
tests/e2e/lib/gridObjectTestUtils.spec.js
tests/e2e/lib/gridTestUtils.spec.js

The changes to ng-grid have been sent to the upstream in these pull requests:
https://github.com/angular-ui/ng-grid/pull/3787
https://github.com/angular-ui/ng-grid/pull/3788
Tests are still passing:

Refactor admin e2e tests.

---

src/web/js/controllers/customer/CustomerOrderLeaveAReviewController.js
src/web/templates/customer/order-leave-a-review.html

Ask permission for publishing reviews on website.

---

src/web/js/controllers/admin/AdminEditOrderController.js

Make deletion reason required.

---

src/web/templates/directives/cp-history-table.html

Show which user caused each history event.

---

src/web/scss/partials/_cp-dashboard.scss
src/web/templates/customer/dashboard.html

Add text if next order has not been accepted.

---

src/web/js/config.js
src/web/js/controllers/admin/AdminEditReviewController.js
src/web/js/controllers/admin/AdminReviewsController.js
src/web/templates/admin/edit-review.html
src/web/templates/admin/reviews.html
src/web/templates/general/staff-nav-menu-items.html
tests/e2e/admin/Reviews.js
tests/e2e/general/NavigationMenu.js

Add Review admin pages.

---

src/web/js/controllers/vendor/VendorPortalAddressController.js
src/web/js/controllers/vendor/VendorSignupController.js
src/web/js/directives/cpAddressFormDirective.js
src/web/js/directives/cpPackageFormDirective.js
src/web/templates/admin/edit-vendor.html
src/web/templates/directives/cp-address-form-for-vendor.html
src/web/templates/vendor/addresses.html
src/web/templates/vendor/vendor-package.html
tests/e2e/customer/Addresses.js
tests/e2e/vendor/CreatePackage.js
tests/e2e/vendor/EditPackage.js
tests/e2e/vendor/YourAddresses.js

Allow multiple order notification mobiles per vendor address.

---

src/web/js/directives/cpAddressFormDirective.js
src/web/js/directives/cpPackageFormDirective.js
tests/unit/directives/cpAddressFormDirective.spec.js

Fix splitting comma-seperated mobile numbers, and add unit tests.

---

package.json
src/web/js/controllers/customer/CustomerPayOnAccountController.js

Fix customer pay on account API call.

---

src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/templates/admin/edit-customer.html
tests/e2e/admin/Customer.js

Add edit forms for pay on account details.

---

bin/load-db-fixtures
src/web/js/controllers/admin/AdminInvoicesController.js
tests/e2e/admin/Invoice.js
tests/e2e/admin/Invoices.js
tests/e2e/admin/Orders.js

Add overdue field to admin invoices page.

---

src/web/js/services/CheckoutService.js

Checkout service fixes

---

src/web/js/directives/cpAddressFormDirective.js
src/web/js/directives/cpPackageFormDirective.js
src/web/templates/directives/cp-address-form-for-vendor.html
src/web/templates/vendor/vendor-package.html
tests/e2e/customer/Addresses.js
tests/e2e/vendor/CreatePackage.js
tests/e2e/vendor/EditPackage.js
tests/e2e/vendor/YourAddresses.js
tests/unit/directives/cpAddressFormDirective.spec.js

Fix spelling: seperated -> separated.

---

app/Resources/views/base.html.twig
src/web/js/controllers/auth/MealPlanCreateAccountController.js
src/web/js/controllers/general/SearchController.js
src/web/js/services/FacebookAnalyticsService.js

Add Facebook tracking to the search page.

---

src/web/js/controllers/admin/AdminOrdersController.js

Fix 'get visible order IDs' button

---

src/web/js/controllers/auth/RegisterController.js
src/web/js/controllers/general/ViewPackageController.js
src/web/js/services/SecurityService.js
src/web/templates/general/view-package.html
tests/e2e/general/Package.js

Change login modal on package page to display once Order button is clicked

---

Gruntfile.js
bin/run-protractor-split
etc/protractor.js
package.json
src/web/js/app.module.js
src/web/js/config.js
src/web/js/controllers/team/TeamMenuController.js
src/web/js/controllers/team/TeamOrderController.js
src/web/js/directives/cpPackageDetailDirective.js
src/web/scss/directives/cp-package-detail.scss
src/web/scss/main.scss
src/web/scss/team/order.scss
src/web/templates/directives/cp-package-detail.html
src/web/templates/team/menu.html
src/web/templates/team/order.html
tests/e2e/team/1_Init.js
tests/e2e/team/Menu.js
tests/e2e/team/ReviewPastOrder.js

Add team menu and review pages.

---

src/web/templates/general/view-package.html
tests/e2e/general/Checkout.js
tests/e2e/team/Menu.js

In this morning's frenzy, I skipped running the automated tests, which just made everything worse and broke the order process. This fixes everything.

Fix broken e2e tests.

---

src/web/js/config.js
src/web/js/controllers/customer/CustomerOrderTeamReviewsController.js
src/web/scss/customer/order-team-reviews.scss
src/web/scss/main.scss
src/web/scss/vendor/orders.scss
src/web/templates/customer/order-team-reviews.html
src/web/templates/customer/orders.html
tests/e2e/customer/OrderTeamReviews.js

Add page for customer to see team reviews.

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminMasqueradeLogoutController.js
src/web/js/controllers/admin/AdminUsersController.js
src/web/js/controllers/general/HeaderController.js
src/web/js/services/SecurityService.js
src/web/scss/directives/cp-header.scss
src/web/templates/admin/masquerade-logout.html
src/web/templates/general/customer-nav-menu-items.html
src/web/templates/general/vendor-nav-menu-items.html
tests/e2e/general/NavigationMenu.js

Add Back To Admin button for masquerading.

---

src/web/js/controllers/admin/AdminInvoicesController.js
src/web/js/controllers/admin/AdminOrdersController.js

Show company name before office manager name in staff orders/invoices tables

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminMealPlanReplacePackageController.js
src/web/js/directives/cpReviewMealPlanDirective.js
src/web/scss/admin/meal-plan-replace-package.scss
src/web/scss/main.scss
src/web/templates/admin/meal-plan-replace-package.html
src/web/templates/admin/meal-plan-review.html
src/web/templates/admin/meal-plans.html
src/web/templates/directives/cp-review-meal-plan.html
tests/e2e/admin/MealPlanReview.js

The failed test is unrelated (a date format check does not work for today's date; will fix this in another pull request).

CPD-243 - Meal Plan: Add search bar to customer dashboard

---

src/web/templates/general/view-vendor.html
tests/e2e/team/Menu.js

Fix test broken by date formatter not working for 10 July.

---

src/web/js/directives/cpVendorProfileFormDirective.js

The split to a named controller will allow unit tests for CPD-297.
This commit does not change any functionality, it's just cosmetics.

cpVendorProfileFormDirective: split controller into named controller.

---

src/web/js/directives/cpVendorProfileFormDirective.js
src/web/templates/vendor/vendor-profile.html
tests/unit/directives/cpVendorProfileFormDirective.spec.js

Allow vendor to set profile cover image and delete profile image.

---

src/web/js/controllers/customer/meal-plan/CustomerMealPlanReviewController.js

Friendlier login workflow when logged out and trying to view a meal plan

---

package.json
src/web/js/controllers/admin/AdminEditPackageController.js
src/web/js/directives/cpPackageFormDirective.js
src/web/templates/admin/edit-package.html
tests/e2e/admin/Package.js
tests/e2e/vendor/EditPackage.js

Remove max 24 hours notice limit on meal plan packages.

---

Gruntfile.js
package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminPromoCodesController.js
src/web/templates/admin/promo-codes/list.html
src/web/templates/general/staff-nav-menu-items.html
tests/e2e/admin/PromoCodes.js
tests/e2e/general/NavigationMenu.js

Add page to view list of all promo codes.

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminCreatePromoCodeController.js
src/web/templates/admin/promo-codes/create.html
src/web/templates/admin/promo-codes/list.html
tests/e2e/admin/CreatePromoCode.js
tests/e2e/admin/PromoCodes.js

Add page to create promo codes.

---

src/web/js/app.module.js
src/web/js/controllers/general/CheckoutPaymentController.js
tests/e2e/general/Checkout.js

Prep for CPD-179

---

src/web/js/controllers/general/CheckoutPaymentController.js
src/web/js/controllers/general/ViewPackageController.js
src/web/js/services/GoogleAnalyticsService.js

The failure below is a known failure on Sundays. It's not a bug.

Add Google Analytics ecommerce integration.

---

package.json
src/web/js/app.module.js
src/web/js/controllers/general/CheckoutPaymentController.js
src/web/templates/general/checkout-payment.html
tests/e2e/general/Checkout.js
tests/unit/controllers/general/CheckoutPaymentController.spec.js
tests/unit/helpers.js

Ask questions when checking out with a referral code.

---

package.json
src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/templates/admin/edit-customer.html
tests/e2e/admin/Customer.js

Add field to edit customer sales staff type to 'edit customer' page.

---

src/web/js/controllers/admin/AdminPromoCodesController.js
src/web/js/cpLibIntegration.js
src/web/js/services/SecurityService.js
tests/e2e/general/Checkout.js

These errors happened because I forgot to install the pre-commit hook on my new laptop!

Fix JSHint errors.

---

package.json
src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/js/controllers/admin/AdminMealPlanSetupPaymentController.js
src/web/js/controllers/customer/CustomerPayOnAccountController.js
src/web/templates/admin/edit-customer.html
tests/e2e/customer/PayOnAccount.js

Use newly merged customer pay-on-account details API.

---

tests/e2e/admin/Customers.js
tests/e2e/admin/DatabaseQuery.js
tests/e2e/admin/PromoCodes.js
tests/e2e/admin/Users.js

API change: https://github.com/CityPantry/citypantry-3-api/pull/547

Update e2e tests now that there is a new fixture customer.

---

package.json
src/web/js/controllers/general/CheckoutPaymentController.js
src/web/templates/general/checkout-payment.html
tests/e2e/general/Checkout.js
tests/unit/controllers/general/CheckoutPaymentController.spec.js

Don't require payment details if 100% discount used.

---

src/web/templates/general/staff-nav-menu-items.html
tests/e2e/general/NavigationMenu.js

Add search link to staff navigation.

---

src/web/js/controllers/auth/RegisterController.js
src/web/templates/auth/register.html
tests/e2e/authentication/Register.js

Add self-identitied personas to the customer registration page.

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminUserController.js
src/web/js/controllers/admin/AdminUsersController.js
src/web/templates/admin/user.html
tests/e2e/HistoryTable.js
tests/e2e/admin/User.js

Needed for CPD-260.
Depends on https://github.com/CityPantry/citypantry-3-api/pull/554

Add staff page to view a user's basic details and history.

---

src/web/js/controllers/admin/AdminEditVendorController.js
src/web/js/controllers/admin/AdminUserController.js
src/web/templates/admin/edit-vendor.html
src/web/templates/admin/user.html
tests/e2e/admin/User.js
tests/e2e/admin/Vendor.js

Add user management to the 'edit vendor' staff page.

---

src/web/templates/general/search.html
tests/e2e/general/Search.js

Build:
Ticket: https://citypantry.atlassian.net/browse/CPD-222

Change head count filter in search page to a text input.

---

package.json
src/web/js/controllers/admin/AdminOrdersController.js
src/web/templates/admin/orders.html
tests/e2e/admin/Orders.js

Allow fields to be selected/unselected for the orders CSV download.

---

src/web/js/controllers/admin/AdminCourierOrdersController.js
src/web/js/controllers/admin/AdminOrdersController.js
src/web/js/controllers/admin/AdminOrdersStatsController.js
src/web/js/controllers/admin/AdminSmsCentreController.js
src/web/js/controllers/admin/AdminViewInvoiceController.js
src/web/templates/admin/orders.html

Misc code cosmetics.

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminRandomToolsController.js
src/web/templates/admin/random-tools.html
src/web/templates/general/staff-nav-menu-items.html
tests/e2e/general/NavigationMenu.js

Random tools page

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminUserController.js
src/web/js/controllers/admin/AdminUserPasswordController.js
src/web/templates/admin/user-password.html
src/web/templates/admin/user.html
tests/e2e/admin/UserPassword.js

Add page for staff to change a user's password.

---

package.json
src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/templates/admin/edit-customer.html
tests/e2e/admin/Customer.js

Allow staff to change recipient of customer pay-on-account invoices.

---

package.json
src/web/js/controllers/customer/CustomerAccountDetailsController.js
src/web/js/controllers/user/UserPaymentCardsController.js
src/web/templates/customer/account-details.html
src/web/templates/user/payment-cards.html
tests/e2e/customer/AccountDetails.js

Don't merge - the tests haven't been run. Waiting on the backend API, then I'll add the JS lib method `UsersFactory.deletePaymentCard`.

Allow customers to delete payment cards.

---

package.json
src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/js/controllers/admin/AdminMealPlanSetupDeliveryDetailsController.js
src/web/js/controllers/customer/CustomerAccountDetailsController.js
src/web/js/controllers/customer/CustomerAddressController.js
src/web/js/controllers/customer/CustomerAddressesController.js
src/web/js/controllers/customer/CustomerDashboardController.js
src/web/js/controllers/general/CheckoutDeliveryDetailsController.js
src/web/templates/admin/edit-customer.html
src/web/templates/customer/account-details.html
src/web/templates/customer/addresses.html
src/web/templates/customer/dashboard.html
src/web/templates/general/checkout-delivery-details.html
tests/e2e/admin/MealPlanSetup.js
tests/e2e/customer/Addresses.js
tests/e2e/customer/Dashboard.js
tests/e2e/general/Checkout.js

Depends on https://github.com/CityPantry/citypantry-3-api/pull/581

Update frontend based on address API structure changes.

---

src/web/js/config.js
src/web/js/controllers/customer/CustomerAccountDetailsController.js
src/web/js/controllers/customer/CustomerAddressController.js
src/web/js/controllers/customer/CustomerAddressesController.js
src/web/js/directives/cpAddressFormDirective.js
src/web/scss/customer/addresses.scss
src/web/scss/main.scss
src/web/templates/customer/account-details.html
src/web/templates/customer/address.html
src/web/templates/customer/addresses.html
src/web/templates/directives/cp-address-form-for-billing.html
src/web/templates/directives/cp-address-form-for-delivery.html
src/web/templates/directives/cp-address-form-for-vendor.html
src/web/templates/directives/cp-address-form.html
src/web/templates/vendor/address.html
tests/e2e/customer/AccountDetails.js
tests/e2e/customer/Addresses.js
tests/unit/directives/cpAddressFormDirective.spec.js

CPD-357: let customers manage their billing addresses

---

src/web/js/controllers/customer/CustomerAddressesController.js
src/web/templates/customer/addresses.html
tests/e2e/customer/Addresses.js

Allow customer to set which billing address is for invoices/receipts.

---

src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/js/controllers/admin/AdminEditVendorController.js
src/web/js/controllers/admin/AdminUsersController.js
src/web/js/controllers/general/HeaderController.js
src/web/js/services/SecurityService.js
src/web/templates/admin/edit-customer.html
src/web/templates/admin/edit-vendor.html
tests/e2e/admin/Customer.js
tests/e2e/admin/Vendor.js

CPD-24: allow masquerading from the customer/vendor pages

---

package.json
src/web/js/controllers/admin/AdminCustomersController.js
src/web/templates/admin/customers.html
tests/e2e/admin/Customers.js

Depends on https://github.com/CityPantry/citypantry-3-api/pull/585

Add ability for staff to download list of customers as CSV.

---

src/web/js/controllers/admin/AdminEditCustomerController.js
src/web/templates/admin/edit-customer.html
tests/e2e/admin/Customer.js

Allow customer invoice/receipt address to be changed by staff.

---

src/web/js/controllers/customer/CustomerAddressesController.js
src/web/scss/customer/addresses.scss
src/web/templates/customer/addresses.html
tests/e2e/customer/Addresses.js
tests/e2e/customer/Dashboard.js

Allow customers to delete delivery and billing addresses.

---

package.json
src/web/js/controllers/admin/AdminEditVendorController.js
src/web/js/controllers/admin/AdminUserController.js
src/web/templates/admin/edit-vendor.html
src/web/templates/admin/user.html
tests/e2e/admin/User.js

Add staff ability to edit vendor email and user email

---

src/web/js/directives/cpPackageFormDirective.js
src/web/js/services/AngularticsAnalyticsService.js
src/web/templates/vendor/vendor-portal-create-package.html
src/web/templates/vendor/vendor-portal-edit-package.html
tests/e2e/NotificationModal.js
tests/e2e/vendor/CreatePackage.js
tests/e2e/vendor/EditPackage.js
tests/unit/directives/cpPackageFormDirective.spec.js

Add logging to debug Brekkie Co's problem with saving package form.

---

src/web/js/app.module.js
src/web/js/controllers/customer/CustomerOrderLeaveAReviewController.js
src/web/js/controllers/customer/CustomerOrderTeamReviewsController.js
src/web/js/controllers/customer/meal-plan/CustomerMealPlanReviewController.js
src/web/js/services/SecurityService.js

SecurityService: halt controller execution if user is wrong type.

---

src/web/js/controllers/admin/AdminInvoicesController.js
src/web/js/controllers/admin/AdminOrdersController.js
src/web/js/controllers/customer/meal-plan/CustomerMealPlanEditOrdersController.js
src/web/js/controllers/general/CheckoutPaymentController.js
src/web/js/services/GoogleAnalyticsService.js
src/web/templates/admin/edit-order.html
src/web/templates/customer/dashboard.html
src/web/templates/customer/meal-plan/confirmation.html
src/web/templates/customer/orders.html
src/web/templates/directives/cp-order-details.html
src/web/templates/general/checkout-thank-you.html
src/web/templates/vendor/orders.html

Changes to keep up with backend renaming vouchers to promo codes.

---

src/web/js/controllers/admin/AdminEditDeliveryRadiiController.js
src/web/js/controllers/admin/AdminEditPackageController.js
src/web/js/controllers/admin/AdminPackagesController.js
src/web/js/controllers/admin/AdminVendorsController.js
src/web/js/controllers/general/ViewPackageController.js
src/web/js/controllers/vendor/VendorPortalPackageController.js
src/web/js/controllers/vendor/VendorPortalPackagesController.js
src/web/js/directives/cpPackageFormDirective.js
src/web/js/services/GoogleAnalyticsService.js
src/web/templates/admin/orders-stats.html
src/web/templates/directives/cp-package-card.html
src/web/templates/directives/cp-package-form.html
src/web/templates/general/view-package.html
src/web/templates/vendor/vendor-portal-packages.html
tests/e2e/vendor/CreatePackage.js
tests/e2e/vendor/EditPackage.js
tests/unit/controllers/general/ViewPackageController.spec.js

Update based on API refactoring + split package cost into standard/zero rated costs

---

package.json
src/web/js/controllers/admin/AdminViewInvoiceController.js
src/web/js/controllers/customer/CustomerOrdersController.js
src/web/js/directives/cpCustomerInvoiceDirective.js
src/web/templates/admin/view-invoice.html
tests/e2e/admin/Invoice.js

Staff invoice page improvements

---

src/web/js/directives/cpPackageFormDirective.js
src/web/scss/directives/cp-package-form.scss
src/web/scss/main.scss
src/web/templates/directives/cp-package-form.html
tests/e2e/vendor/CreatePackage.js
tests/e2e/vendor/EditPackage.js

Change package cost collection to allow vendor to add/remove VAT.

---

package.json
src/web/js/controllers/admin/AdminViewInvoiceController.js
src/web/templates/admin/view-invoice.html
tests/e2e/admin/Invoice.js
tests/e2e/admin/Invoices.js

Allow staff to reissue an invoice.

---

src/web/js/controllers/admin/AdminEditPackageController.js
src/web/js/controllers/admin/AdminEditPackagesController.js
src/web/templates/admin/edit-package.html
src/web/templates/admin/edit-packages.html

Depends on https://github.com/CityPantry/citypantry-3-api/pull/612

Allow staff to tag packages as being in the Mayfair trial.

---

package.json
src/web/js/config.js
src/web/js/controllers/admin/AdminVendorsController.js
src/web/templates/admin/vendors.html
tests/e2e/admin/Vendors.js

Allow staff to download vendor data as a CSV.
